def handle_exception(exc_type, exc_value, exc_traceback):
    # 处理异常的代码
    print("An exception occurred: {}".format(str(exc_value)))
